from typing import Protocol

from ..models import Order, OrderResult, Position


class ExecutionVenue(Protocol):
    def place_order(self, order: Order) -> OrderResult: ...
    def close_position(self, symbol: str) -> OrderResult: ...
    def get_position(self, symbol: str) -> Position | None: ...
    def health_check(self) -> bool: ...
